- composer.json
I originally put PHPUnit on the 3.0 branch for PHP5.2 compatibility but
it seems that the 4.0 branch doesn't have namespaces either.
Fixes #14
> Update PHPUnit to the 4.0 branch

- src/facades/wordpress.php
The `$config` can be read with `include_once` within a function, as this will only work the first time around. On all subsequent calls, `include_once` will return `true` instead of the contents, as the file had already been included before.
> Fix broken config include.

- tests/RequirementsCheckerTest.php
Always use the most specific assert to improve the test failure output.
> Use the most specific PHPUnit assert method available.

- src/Whip_RequirementsChecker.php
The type-hint should be `Whip_Message`, not `string`.
> Correct `Whip_RequirementsChecker::getMostRecentMessage()` return type-hint.

- src/Whip_RequirementsChecker.php
For boolean returns, an if-clause can be avoided by directly returning the evaulated condition.
> Optimize conditional return.

- src/messages/Whip_InvalidVersionRequirementMessage.php
As the `body()` message makes use of the `Whip_VersionRequirement::version()` method, type-hinting against the pure interface is not enough. The interface `Whip_Requirement` interface does not have a `version()` method.
> Correct versioned requirement type-hint.

- src/presenters/Whip_WPMessagePresenter.php
When the `admin_notices` hook is created, raise a flag in a global variable to avoid hooking multiple times.
See #36 
I would like to add tests coverage to this whole class, but I'd need to add `10up/wp_mock`, `lucatume/function-mocker` or something similar to mock global functions such as `wp_kses`.
If that's not a problem, I can add tests to this PR in a separate commit.
> Prevent duplicate notices

- .travis.yml
- composer.json
- src/Whip_MessageDismisser.php
- src/Whip_WPDismissOption.php
- src/facades/wordpress.php
- src/interfaces/Whip_DismissStorage.php
- src/presenters/Whip_WPMessagePresenter.php
- tests/MessageDismisserTest.php
Instead of checking on major WP Version change we are now showing the notice every 4 weeks.
Test instructions
* Get this branch into WordPress SEO
* Change the threshold [dependency value in dismisser declaration](https://github.com/Yoast/whip/compare/42-show-notice-every-4-weeks?expand=1#diff-f04337685746b3069189252b50ae45dcR28) into a value that is easier to test. For example: 2 minutes.
Fixes #42
> Show notice every 4 weeks

- src/facades/wordpress.php
- src/presenters/Whip_WPMessagePresenter.php
> Effectively revert #37 in favor of a hook-based solution for duplicate notices

- src/Whip_RequirementsChecker.php
Historically, this library uses `camelCaps` for variable names instead of the WP convention of using `snake_case`.
There is no need to change this, we just need to allow for it and fix up the few exceptions to the rules.
This commit fixes the exceptions. As these are all local variables within function scopes, there is no backward-compatibility break by changing these names.
> CS: variable naming consistency

- src/facades/wordpress.php
- src/presenters/Whip_WPMessagePresenter.php
Historically, this library uses `camelCaps` for function names instead of the WP convention of using `snake_case`.
There is no need to change this, we just need to allow for it and fix up the one exception to the rules (and allow for one more, but that will be handled via the PHPCS ruleset).
As this involves a `public` method, this *can* be considered a BC-break. However, the reason for the method to be `public` is that it is hooked in via `add_action()`, not because it is a method which external parties are expected to call on, so I expect the BC-break to be theoretical and not to have any impact in practical terms.
> CS: function naming consistency

- src/presenters/Whip_WPMessagePresenter.php
Minor output escaping fixes.
Also whitelists one output call for which all the parts are correctly escaped before being passed to the output call. This whitelisting will take effect once YoastCS 0.5 has been activated.
> CS/XSS: correctly escape output

- src/facades/wordpress.php
- tests/MessageDismisserTest.php
... to prevent issues with operator precedence.
> CS/QA: always use parentheses around calculations

- composer.json
This dependency will prevent packages with known security issues from being installed through Composer.
The package will always have to be at `dev-master` to make sure that the latest security information available will be used.
Refs:
* https://github.com/Roave/SecurityAdvisories
* https://www.bleepingcomputer.com/news/security/php-community-takes-steps-to-stop-installation-of-libraries-with-unpatched-bugs/
* https://websec.io/2018/03/10/Package-Protection-Roave-SecurityAdvisories.html
> Security: add Roave/SecurityAdvisories dependency

- src/Whip_VersionRequirement.php
Using the `x` modifier allows for using comments within a regex itself removing the need for the concatenation previously used.
The `x` modifier ignores all whitespace within the regex, allowing for a nice layout as well.
To facilitate this, I've moved the regex delimiters up into the regex string, so the modifier and the regex stay together.
Refs:
* http://php.net/manual/en/reference.pcre.pattern.modifiers.php
No need to remember sub-matches which are not being used anyway (previously match 2 and 3). The parentheses were in this case also not needed for grouping, so removing them was the simplest fix.
There are already unit tests in place which cover this method comprehensively, so if I did things right, those should still pass. Sic: *and they pass as expected*
> CS: improve regex

- src/messages/Whip_HostMessage.php
Introduced in 1058f244fe6b478a26b02bef8100b943a0cb76d7, the implementation was changed in 2c129ef69a3d408973be66ac85309514355e95b4, however, the now superfluous property and function call parameter were not removed.
> Clean up: Remove unused property and function call parameter

- src/Whip_Configuration.php
- src/Whip_VersionRequirement.php
- src/exceptions/Whip_InvalidType.php
- src/messages/Whip_BasicMessage.php
- tests/MessageTest.php
- tests/VersionRequirementTest.php
* The parameter order for most calls to this Exception was incorrect.
* Where it was correct, a `gettype()` was used, while this is already done in the exception class itself, leading to incorrect results.
* Includes improvement to the parameter documentation of the Exception constructor.
* Includes unit tests proving the bug and safeguarding against it in the future.
> InvalidType Exception: fix the various calls to this Exception

- src/Whip_RequirementsChecker.php
- src/facades/wordpress.php
- src/messages/Whip_HostMessage.php
- src/messages/Whip_UpgradePhpMessage.php
The text-domain for WordPress itself is `default`, not `wordpress`.
Includes minor efficiency fix for `sprintf()`: when using numbered replacements, you can use the same replacement twice, so no need to have `'</a>'` twice in the replacement list.
AFAIK WHIP is intended to also be usable by other (non-Yoast) plugins/themes.
There were currently two phrases which made this awkward.
This PR changes those.
For the first phrase, I've chosen to change `WordPress and Yoast SEO` to `WordPress and all it's plugins and themes`. This incidentally fixes issue #35. /cc @afercia 
If it is preferred that `Yoast SEO` not be removed, I would suggest the following:
* Move the name out of the text string and put it back in using `sprintf()`.
* Make the name filterable to allow other plugins to pass in …
> I18n: various fixes

- src/Whip_Configuration.php
- src/Whip_Host.php
- src/Whip_MessageDismisser.php
- src/Whip_RequirementsChecker.php
- src/Whip_VersionRequirement.php
- src/Whip_WPDismissOption.php
- src/Whip_WPMessageDismissListener.php
- src/exceptions/Whip_InvalidVersionComparisonString.php
- src/interfaces/Whip_Message.php
- src/interfaces/Whip_Requirement.php
- src/messages/Whip_BasicMessage.php
- src/messages/Whip_HostMessage.php
- src/messages/Whip_InvalidVersionRequirementMessage.php
- src/messages/Whip_NullMessage.php
- src/messages/Whip_UpgradePhpMessage.php
- src/presenters/Whip_WPMessagePresenter.php
* Add short descriptions to various functions, properties and function parameters.
* Add missing function docblocks.
* Move some `@throws` tags which were placed with the wrong function.
* Add short descriptions to all `@throws` tags.
* Fix incorrect documentation
- `Whip_InvalidVersionRequirementMessage::__construct()` `$detected` description: `if found` versus `if not found`
> Documentation: various fixes

- src/Whip_VersionRequirement.php
- src/exceptions/Whip_InvalidOperatorType.php
- tests/VersionRequirementTest.php
The `$validOperators` were defined in two places, making the chance of these two arrays getting out of sync large and lowering maintainability.
I've now:
* Removed the `$validOperators` property in the `Whip_InvalidOperatorType` class in favour of adding a new parameter to the constructor.
* The one call to the Exception will now pass the operators against which it validates.
* The message text of the Exception is now unit tested.
> InvalidOperatorType Exception: improve documentation, duplicate code and unit test

- .travis.yml
Having the line to `remove phpunit` underneath the `install` command, makes that it has no effect at the time of the initial install, moving it up fixes this.
Also removed the `selfupdate` command in line with the Travis script in other plugins/modules.
> Travis: don't install PHPUnit when not needed

- .gitignore
- .phpcs.xml.dist
- .travis.yml
- composer.json
This PR can be summarized in the following changelog entry:
* _N/A_
This PR moves this repo onto [YoastCS](https://github.com/Yoast/yoastcs) 0.5.
Please see the individual commits for details and complete documentation about the changes.
* Fixed the YoastCS dependency to the `0.5.*` range.
* Added a ruleset file.
* Excluded existing function and vairable name rules and added different ones as this library uses camelCaps.
* Added configuration for various WPCS sniffs to increase their usefulness.
See [WPCS Customizable sniff properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) for detailed information.
* Added a few temporary exclusions:
- One for a WPCS bug which will be fixed in the WPCS `1.0.0` release;
- Three for …
> CS: start using YoastCS 0.5

- .phpcs.xml.dist
Use the new property array format. The old format is still supported for now, but will be removed in PHPCS 4.0.
See: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0
As this repo does not have a `composer.lock` file, no other changes are needed AFAICS.
> CS: Update PHPCS ruleset for PHPCS 3.3.0

- .phpcs.xml.dist
- composer.json
- src/Whip_RequirementsChecker.php
- src/Whip_WPDismissOption.php
- src/Whip_WPMessageDismissListener.php
- src/facades/wordpress.php
- src/interfaces/Whip_DismissStorage.php
- src/interfaces/Whip_Listener.php
- src/messages/Whip_UpgradePhpMessage.php
- src/presenters/Whip_WPMessagePresenter.php
- tests/ConfigurationTest.php
- tests/MessageDismisserTest.php
- tests/MessagesManagerTest.php
* Remove an exclusion for a false positive which was fixed in WPCS 1.0.0.
* Remove an exclusion for a bug in PHPCS which was fixed in PHPCS 3.3.1.
* The `EscapeOutput` sniff has been moved to the `Security` category in WPCS 1.0.0.
> PHPCS: Update to use YoastCS 1.0 / WPCS 1.0

- .phpcs.xml.dist
- src/Whip_RequirementsChecker.php
- tests/ConfigurationTest.php
- tests/MessageDismisserTest.php
- tests/MessageTest.php
- tests/MessagesManagerTest.php
- tests/RequirementsCheckerTest.php
- tests/VersionRequirementTest.php
- tests/doubles/WPCoreFunctionsMock.php
- tests/doubles/Whip_DismissStorageMock.php
This PR can be summarized in the following changelog entry:
* N/A
* Added documentation (mostly descriptions) to the unit tests. 
* Removed the exceptions for the lack of documentation for these files from the `.phpcs.xml.dist` file.
This PR can be tested by following these steps:
* As the changes are just comments in the unit tests nothing should be changed. 
* All unit tests should still pass. 
Fixes #66
> Added documentation to the WHIP unit tests 

- .phpcs.xml.dist
- composer.json
* Includes adding the PHPCS XSD to the custom ruleset which should now be valid as the minimum PHPCS requirement has gone up to PHPCS 3.3.2.
* Includes removing the DealerDirect Composer PHPCS plugin which now comes automatically with YoastCS.
No code CS changes needed.
> Composer: require YoastCS 1.1.0

- .phpcs.xml.dist
- composer.json
Updates the CS requirements to YoastCS 1.2.2.
Includes minor ruleset update for changed sniff error code in WPCS 2.0.0.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/1.2.0
* https://github.com/Yoast/yoastcs/releases/tag/1.2.1
* https://github.com/Yoast/yoastcs/releases/tag/1.2.2
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/2.0.0-RC1
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/2.0.0
> Composer: require YoastCS ^1.2.2

- tests/ConfigurationTest.php
- tests/MessageTest.php
- tests/RequirementsCheckerTest.php
- tests/VersionRequirementTest.php
The comment text for grouped tags should start one space after the longest tag name.
> Test documentation: align the contents of tags

- composer.json
- phpunit.xml.dist
- tests/bootstrap.php
To test the code in this repository on all supported stable PHP versions, PHPUnit 3.x up to 7.x should be supported.
PHP 5.2 needs PHPUnit 3.x
PHPUnit 4.x will run on PHP 5.3. - 5.6.
PHPUnit 5.x will run on PHP 5.6 - 7.1.
PHPUnit 6.x will run on PHP 7.0 - 7.2.
PHPUnit 7.x will run on PHP 7.1 - 7.3.
For now, PHPUnit 7.x will also work fine for PHP 7.4 (unstable), so supporting PHPUnit 8.x is not yet necessary.
Ref: https://phpunit.de/supported-versions.html
As WHIP is about motivating people to upgrade to higher PHP versions, dropping support for PHP 5.2/PHPUnit 3.x is not (yet) a good idea.
With that in mind, the simplest change has been made to allow the unit tests to be cross-version compatible.
The specs for the `phpunit.xml.dist` file have changed numerous times over the years with …
> QA: PHPUnit cross-version compatibility

- tests/ConfigurationTest.php
- tests/MessageDismisserTest.php
- tests/RequirementsCheckerTest.php
- tests/VersionRequirementTest.php
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available has been extended  hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
This implements this for WHIP, while keeping in mind that at this time, PHPUnit 3.x should still be supported.
Refs:
* https://phpunit.de/manual/3.6/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.assertions
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* …
> QA: use the most specific PHPUnit assertion possible

- tests/bootstrap.php
Show an instructive error message when the Composer autoload file can not be found.
Without this change a fatal PHP error would be shown which isn't very helpful to people new to the repo.
> Test bootstrap: show friendly error message on failure

- tests/RequirementsCheckerTest.php
* The `version_compare()` function expects string input, so the floats passed as the second parameter should be strings.
Ref: https://www.php.net/manual/en/function.version-compare.php
* Made sure skipped tests will always have an explanation on why the test is skipped.
Ref: https://phpunit.de/manual/6.5/en/incomplete-and-skipped-tests.html#incomplete-and-skipped-tests.skipping-tests
> Tests: improve test skipping

- tests/ConfigurationTest.php
Each test should have a `@covers` tag in the function docblock to document what is being tested and to make sure that no accidental code coverage will be recorded.
For more information, see: https://github.com/Yoast/yoastcs/issues/123
> Tests: add missing @covers tag

- tests/ConfigurationTest.php
- tests/MessageDismisserTest.php
- tests/MessageTest.php
- tests/MessagesManagerTest.php
- tests/RequirementsCheckerTest.php
- tests/VersionRequirementTest.php
`@covers` tags are used to indicate what class/method/function a test covers when calculating code coverage of the tests and should follow the specifications of PHPUnit.
Ref:
* https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.covers
* https://github.com/Yoast/yoastcs/issues/123
>  Test documentation: fix @covers tags

- src/messages/Whip_HostMessage.php
- src/messages/Whip_UpgradePhpMessage.php
`implode()` takes two parameters, `$glue` and `$pieces`.
For historical reasons, `implode()` accepted these parameters in either order, though it was recommended to use the documented argument order of `implode( $glue, $pieces )`.
PHP 7.4 deprecates the tolerance for passing the parameters for `implode()` in reverse order.
PHP 8.0 is expected to remove the tolerance for this completely.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
* https://php.net/manual/en/function.implode.php
I've turned on a build against `master`: https://travis-ci.org/Yoast/whip/jobs/565998239
As you can see, the Travis builds on PHP 7.4 are failing. This is caused by the above issue.
When you look at the Travis output for this PR - https://travis-ci.org/Yoast/whip/jobs/565996627 …
> PHP 7.4 compatibility fix / implode argument order

- .phpcs.xml.dist
- .travis.yml
- composer.json
Ruleset updates:
* Remove dependencies related `exclude-pattern`. These are now contained within the YoastCS ruleset as of v1.3.0.
* Set the `minimum_supported_version` via setting a property instead of as a `config` directive.
As of YoastCS 1.3.0, a default is set in the `Yoast` ruleset. The default in the `Yoast` ruleset at this time is `4.9`.
As this repo is compatible with and should still support older WP version, we overrule that value with a repo specific one.
* Change the _temporary adjustment_ for the `WordPress.WP.I18n` sniff.
Up to now, this sniff would show `warning`s instead of `error`s and the build would ignore warnings when determining the pass/fail.
As of now - until the issue is fixed - this specific I18n issue will be ignored for those files containing it and CS …
> Composer: require YoastCS ^1.3.0 & update ruleset

- .travis.yml
As of now, PHP 7.4 is no longer allowed to fail.
Also adding a build against `nightly` (= PHP 8). For now, this build will only lint the code, not run the unit tests this will need PHPUnit 8/9 and the unit test suite is not (yet) compatible with those versions.
> Travis: PHP 7.4/nightly tweaks

- .phpcs.xml.dist
- composer.json
This updates the dependency in `composer.json`, as well as the PHPCS ruleset for YoastCS 2.0.0.
Includes leaving the minimum supported PHP version explicitly at PHP 5.2 for this repo.
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.0.0
> PHPCS: Update to YoastCS 2.0.0

- src/Whip_Host.php
- src/Whip_VersionRequirement.php
- src/exceptions/Whip_InvalidOperatorType.php
- tests/MessageDismisserTest.php
- tests/VersionRequirementTest.php
- tests/doubles/Whip_DismissStorageMock.php
It's `@return` not `@returns`.
... and remove a superfluous `@throws` for a test which doesn't `throw`.
> Docs: various tweaks

- src/Whip_RequirementsChecker.php
Further iteration on #93
As `version_compare()` can return boolean when the third parameter is used, there is no need for the compare here anyway.
Ref: https://www.php.net/manual/en/function.version-compare.php#refsect1-function.version-compare-returnvalues
> QA: remove unnecessary comparison in return

- .travis.yml
- README.md
- composer.json
- tests/bootstrap.php
:warning: **Changelog entry needed** :warning: 
Composer:
* Remove the `xrstf/composer-php52` Composer plugin and the associated scripts.
* Set the minimum supported PHP version to 5.3, including for the PHPCS run.
Travis:
* Drop build on PHP 5.2 and remove associated conditions.
Readme:
* Update the list of supported versions.
> Drop support for PHP 5.2

- .travis.yml
.. to make sure that the command doesn't need to be updated in two places if anything changes.
**Note**: in this case, it was already problematic as the Composer script - correctly - overrules the supported PHP versions to be used with the PHPCompatibility standard, while the command in the Travis script did not and therefore wasn't checking the codebase for compatibility with PHP 5.3-5.5.
Luckily no issues were introduced in the mean time...
> Travis: use the Composer PHPCS script

- composer.json
* Update minimum allowed version of YoastCS from `2.0.0` to `2.1.0`.
As this module does not have a committed `composer.lock` file, all other related updates will be pulled in automatically, including version `0.7.0` from the DealerDirect Composer plugin (which is  compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/2.1.0
> Composer: update YoastCS to v 2.1.0

- .gitignore
- .phpcs.xml.dist
- .travis.yml
- composer.json
- tests/ConfigurationTest.php
- tests/MessageDismisserTest.php
- tests/MessageTest.php
- tests/MessagesManagerTest.php
- tests/RequirementsCheckerTest.php
- tests/TestCase.php
- tests/VersionRequirementTest.php
- tests/bootstrap.php
**TL;DR**: The tests will now be run against PHP 8 and are currently passing.
---
The Composer `autoload-dev` directive allows for specifying files which should only be autoloadable in a `dev` environment.
By adding this directive to the `composer.json` file, we can get rid of most `require_once` statements in the test suite.
The only one remaining is the loading of the WP Core functions mocks. This could be done via a `files` directive within `autoload-dev`, but then they would always be loaded, while they are only needed in the context of running the tests.
So instead, I've added the `require` for the WP Core functions mock file to the test `bootstrap` file.
A side-effect of this change is that we can get rid of the `setUpBeforeClass()` methods which are problematic for PHPUnit …
> Tests: make the testsuite compatible with PHPUnit 9 and test against PHP 8

- .travis.yml
Since this Friday, Travis now has a PHP 8.0 image available.
This commit adds a new build against PHP 8.0, which is not allowed to fail.
> Travis: add a build against PHP 8.0

- .travis.yml
- composer.json
Update version constraint for PHP Parallel Lint after new release.
The most significant change in this release is that PHP Parallel Lint now also supports PHP 5.3. This allows us to make some simplifications to the Travis script as we, for the most part, no longer need to special case PHP 5.3.
Refs:
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.0
> Composer: update PHP Parallel Lint

- src/presenters/Whip_WPMessagePresenter.php
[Per the Readme](https://github.com/Yoast/whip#backwards-compatibility-policy) - semantic versioning is strictly adhered to.
PR #52 introduced a - albeit minor - BC-break due to renaming the `public` `Whip_WPMessagePresenter::register_hooks()` method to `Whip_WPMessagePresenter::registerHooks()`.
While in practice, the BC-break is probably theoretical, the BC-break should still be mitigated if the next release is to be in the 1.x series and not 2.0.
> Whip_WPMessagePresenter: prevent BC-break

- CHANGELOG.md
ℹ️  Note: this PR is in draft as PR #107 still needs to be merged and included in the 1.2.0 release.
---
The changelog for v 1.0.2 only existed in the 1.0.2 tag.
Includes adding dates to undated release entries.
Ref:
* ddd1e0e
* e9df81e
The changelog for v 1.1.0 only existed in the 1.1.0 tag.
Ref:
* 1ea57a0
* 2fc9da3
* f66106f
The release date has been tentatively set to next **Monday, July 19, 2021**.
> Changelog: prepare for the release of version 1.2.0

- .travis.yml
- composer.json
... which includes PHP Parallel Lint by design, so no need to require it separately anymore.
For CI on PHP 5.3, this does require a small tweak, but that's nothing exciting.
Ref: https://github.com/Yoast/yoastcs/releases
> Composer: update to YoastCS 2.2.0

- .github/workflows/test.yml
... so builds against PHP 8.1 should no longer be allowed to fail.
> GH Actions: PHP 8.1 has been released

- src/Whip_RequirementsChecker.php
Dynamic (non-explicitly declared) property usage is expected to be deprecated as of PHP 8.2 and will become a fatal error in PHP 9.0.
There are a number of ways to mitigate this:
* If it's an accidental typo for a declared property: fix the typo.
* For known properties: declare them on the class.
* For unknown properties: add the magic `__get()`, `__set()` et al methods to the class or let the class extend `stdClass` which has highly optimized versions of these magic methods build in.
* For unknown _use of_ dynamic properties, the `#[AllowDynamicProperties]` attribute can be added to the class. The attribute will automatically be inherited by child classes.
In this case, both the `$configuration` property, as well as the `$messageManager` property (both set in the class constructor) fall …
> Whip_RequirementsChecker: explicitly declare all properties

- .github/workflows/cs.yml
- .github/workflows/test.yml
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version …
> GH Actions: various tweaks

- tests/MessageDismisserTest.php
- tests/VersionRequirementTest.php
This improves the test descriptiveness when using the `--testdox` option as well as making it easier to identify which data set failed.
> Tests: use named data providers

- composer.json
* YoastCS 2.3.0 has been released. Previous version used was `2.2.1`.
Ref: https://github.com/Yoast/yoastcs/releases/tag/2.3.0
* Version 1.0.0 of the Composer PHPCS plugin has been released. Previous version used was `0.7.2`.
Ref: https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases
> Composer: update YoastCS and dependencies

- .github/workflows/test.yml
- .gitignore
- README.md
- composer.json
- phpunit.xml.dist
This commit makes the necessary changes to start recording and uploading code coverage data to Coveralls.
Includes:
* Updating the GH Actions `test` worflow to run the high/low PHP version builds with code coverage and upload the results.
* Updating the PHPUnit config to show an inline code coverage summary, improve the `filter` configuration and force the use of `@covers` tags.
* Ignoring the potentially generated code coverage files in the `build/*` directory to prevent it being committed.
* Adding a script to the `composer.json` file to run code coverage.
* Adding a code coverage badge to the README.
Notes:
* Coverage will be recorded using `Xdebug` as the code coverage driver.
* Recording code coverage can be slow and it is not needed to run it on each build to still get a good idea …
> CI/QA: start recording code coverage

- src/Whip_MessagesManager.php
- src/facades/wordpress.php
- tests/bootstrap.php
As support for PHP < 5.3 has been dropped (in PR #96), the `__DIR__` constant can be safely used.
> Modernize: use __DIR__ instead of dirname( __FILE__ )

- src/Whip_MessageDismisser.php
- src/Whip_WPMessageDismissListener.php
- tests/WPMessageDismissListenerTest.php
- tests/doubles/WPCoreFunctionsMock.php
* Remove `filter_input` usage.
This PR can be summarized in the following changelog entry:
* Removes `filter_input` usage for PHP 8.1 improvements.
* Wrapped the `wp_verify_nonce` in the `Whip_MessageDismisser` for testing purposes.
This PR can be acceptance tested by following these steps:
* This PR has only unit tests.
Fixes #132
> 132 whip php 81 improvements

- composer.json
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
This script has been superseded by the Composer plugin handling this automatically.
These descriptions will be used when a list of the available scripts is requested on the command-line using the `composer list` or `composer run -l` commands.
These descriptions also help document the different scripts for the maintainers of the `composer.json` file.
Ref: https://getcomposer.org/doc/articles/scripts.md#custom-descriptions-
> Composer: various tweaks

- .github/workflows/test.yml
All tests pass at this time (and that should stay that way), so no need to `continue-on-error`.
> GH Actions: enable linting and testing against PHP 8.3

- src/Whip_Host.php
- src/Whip_MessageDismisser.php
- src/Whip_MessageFormatter.php
- src/Whip_MessagesManager.php
- src/Whip_RequirementsChecker.php
- src/Whip_VersionRequirement.php
- src/facades/wordpress.php
- src/interfaces/Whip_MessagePresenter.php
- src/messages/Whip_BasicMessage.php
- src/presenters/Whip_WPMessagePresenter.php
- tests/ConfigurationTest.php
- tests/MessageDismisserTest.php
- tests/MessageTest.php
- tests/MessagesManagerTest.php
- tests/RequirementsCheckerTest.php
- tests/TestCase.php
- tests/VersionRequirementTest.php
- tests/WPMessageDismissListenerTest.php
Align parameter descriptions in docblocks and other minor formatting fixes.
> Docs: various improvements

- tests/MessageDismisserTest.php
- tests/VersionRequirementTest.php
- tests/WPMessageDismissListenerTest.php
As of PHPUnit 10, data providers are (again) expected to be `static` methods.
This updates the test suite to respect that.
> Tests: make dataproviders `static`

- tests/doubles/WPCoreFunctionsMock.php
... to be in line with the current parameter names used in WP Core.
Refs:
* https://developer.wordpress.org/reference/functions/__/
* https://developer.wordpress.org/reference/functions/sanitize_text_field/
* https://developer.wordpress.org/reference/functions/wp_unslash/
> Tests/WPCoreFunctionsMock: rename some function parameters

- src/Whip_MessageDismisser.php
The method is documented as returning a boolean value, but the `wp_verify_nonce()` function returns `int|false`.
Fixed now.
Ref: https://developer.wordpress.org/reference/functions/wp_verify_nonce/
Note: as the test suite does not test with a real WP setup, this bug currently cannot easily be proven, nor safeguarded via a test.
The `WHIP_WPMessageDismissListener::listen()` method uses this function and does have a test, but mocks away the `Whip_MessageDismisser::verifyNonce()` method. The mock correctly returns `true|false`, but that isn't what the reality was doing.
/cc @vraja-pro
> Whip_MessageDismisser::verifyNonce(): bug fix

- src/Whip_WPMessageDismissListener.php
The `Whip_MessageDismisser::verifyNonce()` method expects to be passed a `string`, but if the nonce was not available, it would be passed `null`, which could lead to PHP 8.1 "passing null to non-nullable" deprecation notices (though in this case wouldn't as the underlying [`wp_verify_nonce()`](https://developer.wordpress.org/reference/functions/wp_verify_nonce/) function casts the value to string anyway).
All the same, it is a bug. Fixed now.
Note: as the test suite does not test with a real WP setup, this bug currently cannot easily be safeguarded via a test.
The `WHIP_WPMessageDismissListener::listen()` method does have tests, but mocks away the `Whip_MessageDismisser::verifyNonce()` method, so the mock was hiding the bug.
/cc @vraja-pro
> Whip_WPMessageDismissListener::listen(): bug fix

- composer.json
- tests/TestCase.php
- tests/bootstrap.php
As of PHPUnit 4.8.36 and PHPUnit 5.7.21, PHPUnit contains a _forward_ compatibility layer for the most commonly used PHPUnit classes to make handling the change to namespaced classes in PHPUnit 6.0 more straight-forward.
As support for PHP 5.2 has been dropped from this plugin, we can now use this forward-compatibility layer and no longer need to create a class alias for the PHPUnit `TestCase` ourselves.
> Tests: minor modernization

- src/interfaces/Whip_Requirement.php
- tests/ConfigurationTest.php
The `Whip_RequirementsChecker::requirementIsFulfilled()` method makes unconditional calls to the `version()` and `operator()` methods on an object implementing `Whip_Requirement`, so these methods ought to be made explicitly required for classes implementing the `Whip_Requirement` interface.
Fixed now.
Includes updating some tests to match.
Note: this change may warrant a new major release!
> Whip_Requirement: be explicit about all expected methods

- .github/workflows/test.yml
The tests were already being run against PHP 8.3 and not _allowed to fail_.
However, for this workflow, code coverage should run against the highest PHP version. This commit makes it so.
> GH Actions/test: PHP 8.3 has been released

- .github/workflows/cs.yml
- .github/workflows/test.yml
- .phpcs.xml.dist
- composer.json
- config/composer/actions.php
- tests/Unit/WPMessageDismissListenerTest.php
YoastCS 3.0.0 has been released and is based on WordPressCS 3.0.0.
This commit makes the necessary updates for that:
* Composer: update the requirements.
* PHPCS ruleset:
- Update a few sniff/property names for new names in WordPressCS 3.0.
- Exclude code modernization sniffs which can't be applied to this package yet.
- Enforce strict PSR-4 for the tests.
- Remove a few exclusions which are no longer needed.
- Add a few selective exclusions for specific situations.
* GHA CS workflow:
- Run the CS check on the latest PHP version.
No need to run on PHP 7.4 any more as the deprecations previously encountered were all fixed.
- Change the CS check from a "normal" PHPCS run to a run using the Thresholds report and only reporting on issues found in files changed in the branch.
There are …
> Composer/PHPCS: update to YoastCS 3.0.0

- src/Configuration.php
- src/RequirementsChecker.php
- tests/Unit/RequirementsCheckerTest.php
Not that it really matters in this case as strict types is not being used, so an int will juggle to a string just fine, but still.
> QA/Docs: minor fixes

- CHANGELOG.md
The release date has been tentatively set to next Thursday, December 28, 2023.
> Changelog: prepare for the release of version 2.0.0

- config/composer/actions.php
This changes the implementation of the coding standards threshold check to require that both the `YOASTCS_THRESHOLD_ERRORS` environment variable, as well as the `YOASTCS_THRESHOLD_WARNINGS` environment variable match the current status exactly.
This prevents PR A fixing some issues and forgetting to update the threshold, which then would allow PR B to introduce new issues.
_Note: WHIP currently doesn't use the threshold check in CI as the package is "clean". This commit just makes sure that the threshold implementation is in line with that in other plugins for consistency._
> CS/check thresholds: require exact match for thresholds

- .github/workflows/test.yml
* As the PHP 8.4 builds pass and the PHP 8.4 release is expected later this month, the builds are not _allowed to fail_.
* Update PHP version on which code coverage is run (high should now be 8.4).
> GH Actions: enable linting and testing against PHP 8.4

- composer.json
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
> Composer: normalize the file

- tests/Unit/RequirementsCheckerTest.php
- tests/Unit/WPMessageDismissListenerTest.php
`@covers[DefaultClass]` should always contain fully qualified names for PHPUnit to be able to recognize them properly.
> Tests: fix broken `@covers` tags
